wget https://userweb.jlab.org/~douglas/demos/dem1.d
wget https://userweb.jlab.org/~douglas/demos/dem1.out
wget https://userweb.jlab.org/~douglas/demos/dem2.d
wget https://userweb.jlab.org/~douglas/demos/dem2.out
wget https://userweb.jlab.org/~douglas/demos/dem3.d
wget https://userweb.jlab.org/~douglas/demos/dem3.out
wget https://userweb.jlab.org/~douglas/demos/dem4.d
wget https://userweb.jlab.org/~douglas/demos/dem4.out
wget https://userweb.jlab.org/~douglas/demos/dem5.d
wget https://userweb.jlab.org/~douglas/demos/dem5.out
wget https://userweb.jlab.org/~douglas/demos/dem6.d
wget https://userweb.jlab.org/~douglas/demos/dem6.out
wget https://userweb.jlab.org/~douglas/demos/dem7.d
wget https://userweb.jlab.org/~douglas/demos/dem7.out
wget https://userweb.jlab.org/~douglas/demos/dem10.d
wget https://userweb.jlab.org/~douglas/demos/dem10.out
wget https://userweb.jlab.org/~douglas/demos/dem11.d
wget https://userweb.jlab.org/~douglas/demos/dem11.out
wget https://userweb.jlab.org/~douglas/demos/dem12.d
wget https://userweb.jlab.org/~douglas/demos/dem12.out
wget https://userweb.jlab.org/~douglas/demos/dem13.d
wget https://userweb.jlab.org/~douglas/demos/dem13.out
wget https://userweb.jlab.org/~douglas/demos/dem14.d
wget https://userweb.jlab.org/~douglas/demos/dem14.out
